name: server

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - asgiref=3.6.0
  - backports.zoneinfo=0.2.1
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - django=4.1.7
  - gunicorn=20.1.0
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.8
  - pip=23.0.1
  - python=3.11.0
  - python_abi=3.11
  - readline=8.1.2
  - setuptools=67.4.0
  - sqlparse=0.4.3
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
